config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #Resourceful nested Routing
  resources :users, only: [:index, :show, :new,:create, :edit,:update, :destroy] do
    resources :microposts
  end

root "static_pages#home"
get '/help', to: 'static_pages#help'
get '/about', to: 'static_pages#about'
get '/contact', to: 'static_pages#contact'
get '/signup', to: 'users#new'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts
    has_secure_password
    before_save { self.email = email.downcase }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :name, presence: true, length: { maximum: 50 }

    validates :email, presence: true, length:{ maximum: 255 }, 
    format:{with: VALID_EMAIL_REGEX},
    uniqueness: { case_sensitive: false }

    validates :password, presence: true, length: { minimum: 6 }
    # Returns the hash digest of the given string.
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
    BCrypt::Engine::MIN_COST :
    BCrypt::Engine.co
    st
    BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    def create 
        @user = User.find(params[:user_id])
        @micropost = @user.microposts.create(comments_params)
        redirect_to user_path(@user)
    end

    private
    def comments_params 
        params.require(:micropost).permit(:title,:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create 
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
        # Log the user in and redirect to the user's show page.
            log_in (user)
            redirect_to user
        else
            flash.now[:danger] = 'Invalid email/password combination'
            render 'new', status: :unprocessable_entity
        end

    end

    def destroy
        log_out
        redirect_to root_url, status: :see_other
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home 

    end
    def help

    end

    def about
        
    end
    def contact
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the Sample App!"
            redirect_to @user
        else
            
            render :new, status: :bad_request
        end
    end

    def edit 
        @user = User.find(params[:id])
    end

    def update 
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash.notice
            redirect_to @user
        else
            render :edit
        end
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash.notice = "Successfully Deleted."
        redirect_to root_path
    end
    private
        def user_params
            params.require(:user).permit(:name,:email,:password,:password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
        base_title
        else
        page_title + " | " + base_title
        end
    end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
def log_in(user)
    session[:user_id] = user.id
    end

    # Returns the current logged-in user (if any).
    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    # Logs out the current user.
    def log_out
        reset_session
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper    
   

def display_standard_table(users)
    columns = ["Name","Option"]
    thead = content_tag :thead do
        content_tag :tr do
         columns.collect {|column|  concat content_tag(:th,column,scope: 'col')}.join().html_safe
        end
      end
     
      tbody = content_tag :tbody do
       users.collect { |user|
         content_tag :tr do
           columns.collect { |column|
               concat content_tag(:td, user.name)
           }.to_s.html_safe
         end
       }.join().html_safe
      end
      content_tag :table, thead.concat(tbody)
     end 

     def gravatar_for(user, options = { size: 80 })
      size = options[:size]
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "shared/shim" %>
  </head>

  <body>
    <%= render "shared/navbar" %>
   <div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(@user.errors.count, "error") %>.
</div>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
<small>
The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="https://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/shared/_form_user.html.erb
<div class='row'>
    <div class= "col-md-6 col-md-offset-3">
<%= form_with model: @user do|form|%>
<%= render "shared/error_messages" %>   


<div class="mb-3">
    <%= form.label :name, "Name:", class: 'form-label'%>
    <%= form.text_field :name, class: 'form-control'%>
</div>

<div class="mb-3">
    <%= form.label :Email, "Email:"%>
    <%= form.email_field :email, class: "form-control"%>
</div>

<div class="mb-3">
    <%= form.label :password, "Password:"%>
    <%= form.password_field :password, class: "form-control"%>
</div>

<div class="mb-3">
    <%= form.label :password_confirmation, "Password Confirmation:"%>
    <%= form.password_field :password_confirmation, class: "form-control"%>
</div>

<div class="mb-3">
    <%= form.submit "Sign Up", class: "btn btn-primary"%>
</div>
<% end %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "sample app", root_path, id: "logo" %>
<nav>
<div class="navbar-header">
<button id="hamburger" type="button" class="navbar-toggle
collapsed">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<ul class="d-flex flex-row nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
<li class="dropdown">
<a href="#" id="account" class="dropdown-toggle">
Account 
</a>
<ul id="dropdown-menu" class="dropdown-menu">
<li><%= link_to "Profile", current_user %></li>
<li><%= link_to "Settings", '#' %></li>
<li class="divider"></li>
<li>
<%= link_to "Log out", logout_path,
data: { "turbo-method":
:delete } %>
</li>
</ul>
</li>
<% else %>
<li><%= link_to "Log in", login_path %></li>
<% end %>
</ul>
</nav>
</div>
</header>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title))%> </title>
</head>
<body>
<h1>About</h1>
<p>
The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
Tutorial</em></a>, part of the
<a href="https://www.learnenough.com/">Learn Enough</a> family of
tutorials, is a
<a href="https://www.railstutorial.org/book">book</a> and
<a href="https://screencasts.railstutorial.org/">screencast series</a>
to teach web development with
<a href="https://rubyonrails.org/">Ruby on Rails</a>.
This is the sample app for the tutorial.
</p>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
Contact the Ruby on Rails Tutorial about the sample app at the
<a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<body>
<h1>Help</h1>
<p>
The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
Tutorial</em></a>, part of the
<a href="https://www.learnenough.com/">Learn Enough</a> family of
tutorials, is a
<a href="https://www.railstutorial.org/book">book</a> and
<a href="https://screencasts.railstutorial.org/">screencast series</a>
to teach web development with
<a href="https://rubyonrails.org/">Ruby on Rails</a>.
This is the sample app for the tutorial.
</p>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
<head>
<title><%=full_title(yield(:title))%></title>
</head>
<body>
<div class="center jumbotron">
<h1>Welcome to the Sample App</h1>
<h2>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
 

</body>
</html>

app/views/users/edit.html.erb
<h1>Edit User Information</h1>

<%= render "shared/form_user" %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<ul class="users">
<% @users.each do |user| %>
<li>
<%= gravatar_for user, size: 50 %>
<%= link_to user.name, user %>
</li>
<% end %>
</ul>

<%
=begin%>
 <%= display_standard_table(@users)%> 
<%
=end%>

    

app/views/users/new.html.erb
<%= provide(:title, 'Sign Up')%>
<h1><%= full_title(yield(:title))%></h1>


<%= render "shared/form_user" %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
<aside class="col-md-4">
<section class="user_info">
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</section>
</aside>
</div>


<h4>Posts</h4>
<% @user.microposts.each do |micropost| %>
<hr>
  <button class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="top"
        data-bs-custom-class="custom-tooltip"
        data-bs-title="This top tooltip is themed via CSS variables.">
    <%= micropost.title %>
  </button>
  <p>
    <%= micropost.body %>
  </p>
  
<% end %>

<h2>Add a post:</h2>
<%= form_with model: [ @user, @user.microposts.build ] do |form| %>
<div class="mb-3">
  <p>
    <%= form.label :Title, "Title:" %><br>
    <%= form.text_field :title, class: "form-control" %>
  </p>
</div>
<div class="mb-3">
  <p>
    <%= form.label :Body, "Body:" %><br>
    <%= form.text_area :body, class: "form-control" %>
  </p>
</div> 
  <p>
    <%= form.submit :Submit ,class: "btn btn-primary" %>
  </p>
<% end %>